#!/usr/bin/env bash
set -euo pipefail
umask 077

: "${HERDR_CONFIG_FILE:?HERDR_CONFIG_FILE is required}"

existing_token=""
if [ -r "$HERDR_CONFIG_FILE" ]; then
    existing_token="$(sed -n 's/^HERDR_RELAY_TOKEN=//p' "$HERDR_CONFIG_FILE" | tail -1)"
    case "$existing_token" in *[!A-Za-z0-9_-]*) existing_token="" ;; esac
fi

relay_token="${HERDR_RELAY_TOKEN:-$existing_token}"
if [ -z "$relay_token" ]; then
    if command -v openssl >/dev/null 2>&1; then
        relay_token="$(openssl rand -hex 32)"
    else
        relay_token="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
    fi
fi

mkdir -p "$(dirname "$HERDR_CONFIG_FILE")"
{
    echo "# herdr-remote configuration (generated by install-service.sh)"
    printf 'HERDR_RELAY_BIND=%q\n' "${HERDR_RELAY_BIND:-127.0.0.1}"
    printf 'HERDR_RELAY_PORT=%q\n' "${HERDR_RELAY_PORT:-8375}"
    printf 'HERDR_RELAY_TOKEN=%q\n' "$relay_token"
    printf 'HERDR_ALLOWED_ORIGINS=%q\n' "${HERDR_ALLOWED_ORIGINS:-}"
    printf 'HERDR_PUBLIC_URL=%q\n' "${HERDR_PUBLIC_URL:-}"
    printf 'HERDR_CONFIG_DIR=%q\n' "${HERDR_CONFIG_DIR:-$(dirname "$HERDR_CONFIG_FILE")}"
    printf 'HERDR_BIN=%q\n' "${HERDR_BIN:-herdr}"
    printf 'HERDR_LOG_DIR=%q\n' "${HERDR_LOG_DIR:-}"
    printf 'HERDR_TUNNEL_MODE=%q\n' "${HERDR_TUNNEL_MODE:-none}"
    printf 'HERDR_TUNNEL_NAME=%q\n' "${HERDR_TUNNEL_NAME:-}"
    printf 'HERDR_TUNNEL_HOSTNAME=%q\n' "${HERDR_TUNNEL_HOSTNAME:-}"
    printf 'HERDR_RELAY_DIR=%q\n' "${HERDR_RELAY_DIR:-}"
    printf 'HERDR_UV_PATH=%q\n' "${HERDR_UV_PATH:-}"
    printf 'HERDR_CLOUDFLARED_PATH=%q\n' "${HERDR_CLOUDFLARED_PATH:-}"
    printf 'HERDR_MAX_CLIENTS=%q\n' "${HERDR_MAX_CLIENTS:-16}"
    printf 'HERDR_MAX_PUSH_SUBSCRIPTIONS=%q\n' "${HERDR_MAX_PUSH_SUBSCRIPTIONS:-64}"
} > "$HERDR_CONFIG_FILE"
chmod 600 "$HERDR_CONFIG_FILE"
